Repository cdktf/cdktf-tf-module-stack, pull requests merged in 2023-08, with the labels that each got.

#257 chore(deps): upgrade dependencies
  .projen/tasks.json
  package.json
  yarn.lock
Labels: auto-approve, dependencies

#258 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve, dependencies

#259 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve, dependencies

#261 feat: upgrade jsii to 5.1.x
  .projen/deps.json
  .projen/tasks.json
  .projenrc.ts
  package.json
  projenrc/custom-docgen.ts
  yarn.lock
Labels: auto-approve, automerge

#262 chore: automate upgrading cdktf itself
  .gitattributes
  .github/workflows/upgrade-cdktf.yml
  .gitignore
  .projen/files.json
  .projenrc.ts
  projenrc/upgrade-cdktf.ts
  scripts/update-cdktf.sh
Labels: auto-approve, automerge

#263 chore!: upgrade to cdktf 0.18.0
  .projen/deps.json
  .projen/tasks.json
  .projenrc.ts
  package.json
  scripts/update-cdktf.sh
  yarn.lock
Labels: auto-approve, automerge, dependencies

#265 chore: remove package-lock.json
  package-lock.json
Labels: auto-approve, automerge

#264 chore: add note to README about package rename
  .projenrc.ts
  README.md
  package.json
Labels: auto-approve, automerge

#266 chore: remove default pull request template
  .gitattributes
  .github/pull_request_template.md
  .gitignore
  .projen/files.json
  .projenrc.ts
Labels: auto-approve, automerge

#267 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve, automerge, dependencies

#268 chore(ci): don't do a release on certain changes
  .github/workflows/release.yml
  .projenrc.ts
Labels: auto-approve, automerge
