Repository cdktf/cdktf-tf-module-stack, pull requests merged in 2025-04, with the labels that each got.

#374 chore(ci): automate jsii & typescript updates
  .github/MAINTENANCE.md
  .github/workflows/upgrade-jsii-typescript.yml
  .projen/deps.json
  .projen/tasks.json
  .projenrc.ts
  package.json
  projenrc/upgrade-jsii-typescript.ts
  scripts/check-jsii-versions.js
  yarn.lock
Labels: auto-approve, automerge

#375 chore(deps): update pinned versions of GitHub Actions
  .github/workflows/build.yml
  .github/workflows/release.yml
  .github/workflows/upgrade-cdktf.yml
  .github/workflows/upgrade-jsii-typescript.yml
  .github/workflows/upgrade-main.yml
  .projenrc.ts
  projenrc/upgrade-cdktf.ts
Labels: auto-approve, automerge

#376 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve, automerge, dependencies

#377 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve, automerge, dependencies

#378 chore(deps): upgrade jsii & typescript to v5.6
  .github/workflows/upgrade-jsii-typescript.yml
  .projen/deps.json
  .projenrc.ts
  package.json
  yarn.lock
Labels: auto-approve, automerge, automated

#379 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve, automerge, dependencies

#381 chore(deps): upgrade dependencies
  package.json
  test/index.test.ts
  tsconfig.dev.json
  yarn.lock
Labels: auto-approve, automerge, dependencies
