Repository cdktf/cdktf-tf-module-stack, pull requests merged in 2025-01, with the labels that each got.

#355 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve, automerge, dependencies

#356 chore(deps): update pinned versions of GitHub Actions
  .github/workflows/auto-approve.yml
  .github/workflows/automerge.yml
  .github/workflows/build.yml
  .github/workflows/release.yml
  .github/workflows/upgrade-cdktf.yml
  .github/workflows/upgrade-main.yml
  .projenrc.ts
Labels: auto-approve, automerge

#358 chore: upgrade jsii & typescript to v5.5
  .github/workflows/upgrade-jsii-typescript.yml
  .projen/deps.json
  .projenrc.ts
  package.json
  yarn.lock
Labels: auto-approve, automerge, automated

#359 docs: create maintenance guide
  .github/MAINTENANCE.md
Labels: auto-approve, automerge

#360 chore(ci): update required version of constructs when cdktf is upgraded
  .github/MAINTENANCE.md
  .github/workflows/upgrade-cdktf.yml
  .projenrc.ts
  projenrc/upgrade-cdktf.ts
  scripts/update-cdktf.sh
Labels: auto-approve, automerge

#361 chore(deps)!: upgrade minimum required version of constructs to 10.3.0
  .projen/deps.json
  .projenrc.ts
  README.md
  docs/csharp.md
  docs/java.md
  docs/python.md
  docs/typescript.md
  package.json
  yarn.lock
Labels: auto-approve, automerge

#362 chore(deps): upgrade dependencies
  .projen/deps.json
  package.json
  yarn.lock
Labels: auto-approve, automerge, dependencies

#363 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve, automerge, dependencies

#364 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve, automerge, dependencies
